### ISSUE TITLE
project-extents

### ISSUE THREAD

**Issue by zoometh** [achp-project/cultural-heritage#12]
Hi @BAPAlveyCHIC , @manojlokare , @razekmh 

The [MAESAM GeoJSON file](https://github.com/achp-project/cultural-heritage/blob/main/map-projects/prj-extent/maesam.geojson) seems corrupted with erros in its coordinates. In [rm_compar.ipynb](https://colab.research.google.com/github/achp-project/cultural-heritage/blob/main/presentation/bhdc/rm_compar.ipynb#scrollTo=LGmZglxCch6b), I have this error:

![image](https://github.com/achp-project/cultural-heritage/assets/67924910/2851665f-2fd0-4a9c-bbca-901315aad04b)

**Comment by razekmh** [comment]
@RHVDM I think we can simplify the geojson a bit. 
@zoometh Do we need the project extent to be exactly matching the country borders? Could it be a bit squared of instead?

**Comment by zoometh** [comment]
@razekmh you can do it as you wish

**Comment by RHVDM** [comment]
Hey Thomas, I thought I did upload them last month, but it seems I did it wrong. I will try again a bit later (have a long meeting) as I do have all the geometries ready.

**Comment by razekmh** [comment]
solved by f2102396f1cc3f36c51eec7fa195443a9575e07a 
There was a bit of nesting that [folium](https://github.com/python-visualization/folium/blob/570f2933dda0cff25c7bbef2cf0c23da8443051c/folium/utilities.py#L271) did not expect. Potentially an issue to improve the library. 
Please reopen if issue persists on your side
